esphome:
  name: barn-thermostat
  friendly_name: barn-thermostat
  on_boot:
    - priority: 90
      then:
        - switch.turn_on: TH_sensor_power

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf  # Or use "arduino" if preferred
        
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Barn-Thermostat Fallback Hotspot"
    password: ""

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: "Barn Thermostat Restart"
    device_class: restart
    entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Barn Thermostat Button"
    on_press:
      then:
        - switch.toggle: relay_1
  - platform: status
    name: "Barn Thermostat Status"

switch:
  - platform: gpio
    name: "Barn Thermostat Relay"
    pin: GPIO21
    id: relay_1
    restore_mode: ALWAYS_OFF
    on_turn_on:
      light.turn_on: power_led
    on_turn_off:
      light.turn_off: power_led

  - platform: gpio
    pin:
      number: GPIO27
    id: TH_sensor_power
    restore_mode: ALWAYS_ON

output:
  - id: power_led_output
    platform: gpio
    pin: 16
    inverted: True

  - id: green_led_output
    platform: gpio
    pin: 13
    inverted: True

light:
  - platform: binary
    id: power_led
    name: "Power LED"
    output: power_led_output
    internal: true

  - platform: binary
    id: green_led
    name: "Green LED"
    output: green_led_output
    internal: true

  - platform: status_led
    name: "Barn Thermostat Wifi LED"
    pin:
      number: GPIO15
      inverted: true
    id: wifi_led
    internal: true

interval:
  - interval: 60s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on: wifi_led
        else:
          - light.turn_off: wifi_led

sensor:
  - platform: dht
    pin: GPIO25
    model: SI7021
    temperature:
      name: "Barn Thermostat Temperature"
      id: barn_thermostat_temp
    humidity:
      name: "Barn Thermostat Humidity"
      id: barn_thermostat_humi
    update_interval: 60s

  - platform: wifi_signal
    name: "Barn Thermostat Wifi RSSI"
    update_interval: 60s

  - platform: uptime
    id: uptime_sensor
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: "Barn Thermostat Uptime"
    id: uptime_human
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: "Barn Thermostat IP"
    mac_address:
      name: "Barn Thermostat MAC Address"

# External Component for SI7021 DHT Sensor
external_components:
  - source:
      type: git
      url: https://github.com/Beungoud/esphome
      ref: fix-esp32-dht-SI7021
    components: ["dht"]

climate:
  - platform: thermostat
    name: "Barn Climate Control Thermostat"
    sensor: barn_thermostat_temp
    visual:
      min_temperature: 5 째C
      max_temperature: 15 째C
      temperature_step: 0.1 째C
    preset:
      - name: "Default"
        default_target_temperature_low: 8 째C
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1
